/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_content_delivery_bucket": "cognito-frontend-bucket-hardik-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "https://doa9mjolraeom.cloudfront.net",
    Auth: {
    Cognito: {
      userPoolId: "ap-south-1_WfTVIuC0l",             // from Outputs
      userPoolClientId: "509ba3lhqgfrueklt9gihc6rc", // from Outputs
      region: "ap-south-1" ,                          // from Output,
      loginWith: {
        oauth: {
          domain: "sam-app-dev.auth.ap-south-1.amazoncognito.com", // from HostedUIDomain Output
          scopes: ["openid", "email", "profile"],
          redirectSignIn: ["http://localhost:4000"],  // same as FrontendUrl param
          redirectSignOut: ["http://localhost:4000"], // same as FrontendUrl param
          responseType: "code"
        }
      }
    }
  }
};
export default awsmobile;
